"""
Comprehensive Nutritional Database for NutriVision AI.
Sources: USDA FoodData Central, Indian Food Composition Tables (IFCT / National Institute of Nutrition), FSSAI Standards.
All macro and micro nutrient values are normalized per 100g of edible portion.
"""

from typing import Dict, Any, List, Optional
import re

FOOD_DATABASE: Dict[str, Dict[str, Any]] = {
    # ------------------ INDIAN SPECIALTIES & GRAINS ------------------
    "paneer_tikka": {
        "name": "Paneer Tikka / Paneer Gravy",
        "category": "Curry / Protein",
        "calories": 265.0,
        "protein": 18.2,
        "carbs": 6.5,
        "fat": 19.1,
        "saturated_fat": 10.5,
        "fiber": 1.2,
        "sugar": 2.1,
        "sodium": 420.0,
        "potassium": 210.0,
        "calcium": 480.0,
        "iron": 1.4,
        "glycemic_index": 20,
        "nutri_score": "B",
        "density": 1.05,
        "typical_serving_g": 180,
        "food_group": "protein",
        "tags": ["vegetarian", "gluten_free", "high_protein", "keto_friendly", "high_calcium"]
    },
    "yellow_dal": {
        "name": "Yellow Dal Tadka (Moong / Toor Lentils)",
        "category": "Lentils / Soup",
        "calories": 116.0,
        "protein": 7.3,
        "carbs": 16.8,
        "fat": 2.4,
        "saturated_fat": 0.6,
        "fiber": 4.8,
        "sugar": 1.1,
        "sodium": 280.0,
        "potassium": 340.0,
        "calcium": 42.0,
        "iron": 2.1,
        "glycemic_index": 32,
        "nutri_score": "A",
        "density": 1.08,
        "typical_serving_g": 180,
        "food_group": "composite",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_fiber", "low_gi"]
    },
    "steamed_basmati_rice": {
        "name": "Steamed White Basmati Rice",
        "category": "Grains",
        "calories": 130.0,
        "protein": 2.7,
        "carbs": 28.2,
        "fat": 0.3,
        "saturated_fat": 0.1,
        "fiber": 0.4,
        "sugar": 0.1,
        "sodium": 2.0,
        "potassium": 35.0,
        "calcium": 10.0,
        "iron": 0.4,
        "glycemic_index": 68,
        "nutri_score": "C",
        "density": 0.85,
        "typical_serving_g": 150,
        "food_group": "carbs",
        "tags": ["vegetarian", "vegan", "gluten_free"]
    },
    "brown_rice": {
        "name": "Steamed Brown Rice",
        "category": "Grains",
        "calories": 111.0,
        "protein": 2.6,
        "carbs": 23.0,
        "fat": 0.9,
        "saturated_fat": 0.2,
        "fiber": 1.8,
        "sugar": 0.4,
        "sodium": 5.0,
        "potassium": 84.0,
        "calcium": 10.0,
        "iron": 0.5,
        "glycemic_index": 50,
        "nutri_score": "A",
        "density": 0.88,
        "typical_serving_g": 150,
        "food_group": "carbs",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_fiber", "low_gi"]
    },
    "whole_wheat_roti": {
        "name": "Whole Wheat Roti / Chapati (Without Ghee)",
        "category": "Breads",
        "calories": 240.0,
        "protein": 8.1,
        "carbs": 48.0,
        "fat": 2.2,
        "saturated_fat": 0.4,
        "fiber": 6.5,
        "sugar": 1.0,
        "sodium": 180.0,
        "potassium": 190.0,
        "calcium": 35.0,
        "iron": 2.8,
        "glycemic_index": 52,
        "nutri_score": "A",
        "density": 0.70,
        "typical_serving_g": 40,
        "food_group": "carbs",
        "tags": ["vegetarian", "vegan", "high_fiber"]
    },
    "cucumber_salad": {
        "name": "Cucumber Tomato Onion Kachumber Salad",
        "category": "Salad / Vegetables",
        "calories": 22.0,
        "protein": 0.9,
        "carbs": 4.2,
        "fat": 0.3,
        "saturated_fat": 0.05,
        "fiber": 1.4,
        "sugar": 2.2,
        "sodium": 45.0,
        "potassium": 180.0,
        "calcium": 18.0,
        "iron": 0.4,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 0.65,
        "typical_serving_g": 100,
        "food_group": "vegetables",
        "tags": ["vegetarian", "vegan", "gluten_free", "low_calorie", "low_gi"]
    },
    "chicken_biryani": {
        "name": "Chicken Dum Biryani",
        "category": "Composite / Meal",
        "calories": 185.0,
        "protein": 11.5,
        "carbs": 21.0,
        "fat": 6.2,
        "saturated_fat": 1.8,
        "fiber": 1.3,
        "sugar": 0.8,
        "sodium": 390.0,
        "potassium": 210.0,
        "calcium": 25.0,
        "iron": 1.2,
        "glycemic_index": 58,
        "nutri_score": "C",
        "density": 0.95,
        "typical_serving_g": 300,
        "food_group": "composite",
        "tags": ["high_protein", "gluten_free"]
    },
    "chana_masala": {
        "name": "Chana Masala (Chickpea Curry)",
        "category": "Curry / Legumes",
        "calories": 138.0,
        "protein": 6.8,
        "carbs": 18.4,
        "fat": 4.5,
        "saturated_fat": 0.6,
        "fiber": 5.2,
        "sugar": 2.3,
        "sodium": 340.0,
        "potassium": 290.0,
        "calcium": 55.0,
        "iron": 2.4,
        "glycemic_index": 30,
        "nutri_score": "A",
        "density": 1.05,
        "typical_serving_g": 200,
        "food_group": "composite",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_fiber", "low_gi"]
    },
    "dal_makhani": {
        "name": "Dal Makhani (Black Lentil Creamy Curry)",
        "category": "Curry / Lentils",
        "calories": 165.0,
        "protein": 5.9,
        "carbs": 15.2,
        "fat": 9.2,
        "saturated_fat": 4.5,
        "fiber": 4.1,
        "sugar": 1.5,
        "sodium": 380.0,
        "potassium": 280.0,
        "calcium": 60.0,
        "iron": 1.9,
        "glycemic_index": 38,
        "nutri_score": "C",
        "density": 1.10,
        "typical_serving_g": 180,
        "food_group": "composite",
        "tags": ["vegetarian", "gluten_free", "high_fiber"]
    },

    # ------------------ LEAN PROTEINS & SEAFOOD ------------------
    "grilled_chicken_breast": {
        "name": "Grilled Herb Chicken Breast",
        "category": "Lean Poultry",
        "calories": 165.0,
        "protein": 31.0,
        "carbs": 0.0,
        "fat": 3.6,
        "saturated_fat": 1.0,
        "fiber": 0.0,
        "sugar": 0.0,
        "sodium": 74.0,
        "potassium": 256.0,
        "calcium": 15.0,
        "iron": 1.0,
        "glycemic_index": 0,
        "nutri_score": "A",
        "density": 1.05,
        "typical_serving_g": 150,
        "food_group": "protein",
        "tags": ["high_protein", "keto_friendly", "gluten_free", "low_carb", "zero_sugar"]
    },
    "grilled_salmon": {
        "name": "Pan-Seared / Grilled Salmon Fillet",
        "category": "Seafood / Healthy Fats",
        "calories": 208.0,
        "protein": 22.0,
        "carbs": 0.0,
        "fat": 13.0,
        "saturated_fat": 2.5,
        "fiber": 0.0,
        "sugar": 0.0,
        "sodium": 59.0,
        "potassium": 384.0,
        "calcium": 12.0,
        "iron": 0.8,
        "glycemic_index": 0,
        "nutri_score": "A",
        "density": 1.04,
        "typical_serving_g": 150,
        "food_group": "protein",
        "tags": ["high_protein", "omega_3", "keto_friendly", "gluten_free", "low_carb"]
    },
    "boiled_egg": {
        "name": "Boiled Whole Egg (Grade A)",
        "category": "Eggs / Protein",
        "calories": 155.0,
        "protein": 13.0,
        "carbs": 1.1,
        "fat": 11.0,
        "saturated_fat": 3.3,
        "fiber": 0.0,
        "sugar": 1.1,
        "sodium": 124.0,
        "potassium": 126.0,
        "calcium": 50.0,
        "iron": 1.2,
        "glycemic_index": 0,
        "nutri_score": "B",
        "density": 1.03,
        "typical_serving_g": 50,
        "food_group": "protein",
        "tags": ["vegetarian", "high_protein", "keto_friendly", "gluten_free"]
    },
    "egg_white": {
        "name": "Steamed / Boiled Egg Whites",
        "category": "Eggs / Lean Protein",
        "calories": 52.0,
        "protein": 11.0,
        "carbs": 0.7,
        "fat": 0.2,
        "saturated_fat": 0.0,
        "fiber": 0.0,
        "sugar": 0.7,
        "sodium": 166.0,
        "potassium": 163.0,
        "calcium": 7.0,
        "iron": 0.1,
        "glycemic_index": 0,
        "nutri_score": "A",
        "density": 1.02,
        "typical_serving_g": 100,
        "food_group": "protein",
        "tags": ["vegetarian", "high_protein", "low_calorie", "zero_fat"]
    },
    "tofu_grilled": {
        "name": "Grilled Organic Firm Tofu",
        "category": "Plant Protein",
        "calories": 144.0,
        "protein": 15.5,
        "carbs": 2.8,
        "fat": 8.5,
        "saturated_fat": 1.3,
        "fiber": 2.1,
        "sugar": 0.6,
        "sodium": 14.0,
        "potassium": 230.0,
        "calcium": 350.0,
        "iron": 2.7,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 0.98,
        "typical_serving_g": 150,
        "food_group": "protein",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_protein", "high_calcium"]
    },

    # ------------------ VEGETABLES & GREENS ------------------
    "steamed_broccoli": {
        "name": "Steamed Fresh Broccoli Florets",
        "category": "Cruciferous Vegetables",
        "calories": 35.0,
        "protein": 2.4,
        "carbs": 7.2,
        "fat": 0.4,
        "saturated_fat": 0.05,
        "fiber": 3.3,
        "sugar": 1.4,
        "sodium": 41.0,
        "potassium": 293.0,
        "calcium": 40.0,
        "iron": 0.7,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 0.55,
        "typical_serving_g": 100,
        "food_group": "vegetables",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_fiber", "low_calorie", "superfood"]
    },
    "steamed_asparagus": {
        "name": "Steamed Green Asparagus Spears",
        "category": "Vegetables",
        "calories": 22.0,
        "protein": 2.4,
        "carbs": 4.1,
        "fat": 0.2,
        "saturated_fat": 0.04,
        "fiber": 2.0,
        "sugar": 1.3,
        "sodium": 14.0,
        "potassium": 224.0,
        "calcium": 23.0,
        "iron": 0.9,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 0.60,
        "typical_serving_g": 80,
        "food_group": "vegetables",
        "tags": ["vegetarian", "vegan", "gluten_free", "low_calorie", "low_sodium"]
    },
    "baby_carrots": {
        "name": "Steamed / Glazed Baby Carrots",
        "category": "Root Vegetables",
        "calories": 35.0,
        "protein": 0.6,
        "carbs": 8.2,
        "fat": 0.1,
        "saturated_fat": 0.02,
        "fiber": 2.5,
        "sugar": 4.8,
        "sodium": 78.0,
        "potassium": 238.0,
        "calcium": 32.0,
        "iron": 0.4,
        "glycemic_index": 39,
        "nutri_score": "A",
        "density": 0.75,
        "typical_serving_g": 70,
        "food_group": "vegetables",
        "tags": ["vegetarian", "vegan", "gluten_free", "vitamin_a"]
    },
    "spinach_sauteed": {
        "name": "Sauteed Garlic Spinach / Palak",
        "category": "Leafy Greens",
        "calories": 40.0,
        "protein": 3.0,
        "carbs": 4.0,
        "fat": 2.0,
        "saturated_fat": 0.3,
        "fiber": 2.4,
        "sugar": 0.5,
        "sodium": 120.0,
        "potassium": 460.0,
        "calcium": 136.0,
        "iron": 3.6,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 0.70,
        "typical_serving_g": 120,
        "food_group": "vegetables",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_iron", "high_potassium"]
    },

    # ------------------ GRAINS, SEEDS & HEALTHY FATS ------------------
    "cooked_quinoa": {
        "name": "Cooked Organic Tri-Color Quinoa",
        "category": "Ancient Grains",
        "calories": 120.0,
        "protein": 4.4,
        "carbs": 21.3,
        "fat": 1.9,
        "saturated_fat": 0.2,
        "fiber": 2.8,
        "sugar": 0.9,
        "sodium": 7.0,
        "potassium": 172.0,
        "calcium": 17.0,
        "iron": 1.5,
        "glycemic_index": 53,
        "nutri_score": "A",
        "density": 0.85,
        "typical_serving_g": 140,
        "food_group": "carbs",
        "tags": ["vegetarian", "vegan", "gluten_free", "complete_protein", "low_gi"]
    },
    "avocado_slices": {
        "name": "Fresh Hass Avocado Slices",
        "category": "Healthy Fats / Fruits",
        "calories": 160.0,
        "protein": 2.0,
        "carbs": 8.5,
        "fat": 14.7,
        "saturated_fat": 2.1,
        "fiber": 6.7,
        "sugar": 0.7,
        "sodium": 7.0,
        "potassium": 485.0,
        "calcium": 12.0,
        "iron": 0.6,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 0.90,
        "typical_serving_g": 60,
        "food_group": "fats",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_fiber", "monounsaturated_fat", "keto_friendly"]
    },
    "feta_cheese": {
        "name": "Greek Feta Cheese Cubes",
        "category": "Dairy / Cheese",
        "calories": 264.0,
        "protein": 14.2,
        "carbs": 4.1,
        "fat": 21.3,
        "saturated_fat": 14.9,
        "fiber": 0.0,
        "sugar": 4.1,
        "sodium": 1116.0,
        "potassium": 62.0,
        "calcium": 493.0,
        "iron": 0.7,
        "glycemic_index": 27,
        "nutri_score": "D",
        "density": 1.02,
        "typical_serving_g": 40,
        "food_group": "dairy",
        "tags": ["vegetarian", "keto_friendly", "high_calcium"]
    },
    "kalamata_olives": {
        "name": "Kalamata Black Olives",
        "category": "Healthy Fats",
        "calories": 115.0,
        "protein": 0.8,
        "carbs": 6.3,
        "fat": 10.7,
        "saturated_fat": 1.4,
        "fiber": 3.2,
        "sugar": 0.0,
        "sodium": 735.0,
        "potassium": 8.0,
        "calcium": 88.0,
        "iron": 3.3,
        "glycemic_index": 15,
        "nutri_score": "C",
        "density": 0.95,
        "typical_serving_g": 30,
        "food_group": "fats",
        "tags": ["vegetarian", "vegan", "gluten_free", "keto_friendly"]
    },
    "rolled_oats_cooked": {
        "name": "Rolled Oatmeal Porridge (Water/Almond Milk)",
        "category": "Breakfast Grains",
        "calories": 71.0,
        "protein": 2.5,
        "carbs": 12.0,
        "fat": 1.5,
        "saturated_fat": 0.3,
        "fiber": 1.7,
        "sugar": 0.3,
        "sodium": 49.0,
        "potassium": 61.0,
        "calcium": 20.0,
        "iron": 0.9,
        "glycemic_index": 55,
        "nutri_score": "A",
        "density": 0.95,
        "typical_serving_g": 200,
        "food_group": "carbs",
        "tags": ["vegetarian", "vegan", "high_fiber", "heart_healthy"]
    },
    "fresh_blueberries": {
        "name": "Fresh Blueberries",
        "category": "Fruits / Berries",
        "calories": 57.0,
        "protein": 0.7,
        "carbs": 14.5,
        "fat": 0.3,
        "saturated_fat": 0.03,
        "fiber": 2.4,
        "sugar": 9.9,
        "sodium": 1.0,
        "potassium": 77.0,
        "calcium": 6.0,
        "iron": 0.3,
        "glycemic_index": 53,
        "nutri_score": "A",
        "density": 0.65,
        "typical_serving_g": 60,
        "food_group": "fruits",
        "tags": ["vegetarian", "vegan", "gluten_free", "antioxidants", "superfood"]
    },
    "banana_slices": {
        "name": "Fresh Banana Coins",
        "category": "Fruits",
        "calories": 89.0,
        "protein": 1.1,
        "carbs": 22.8,
        "fat": 0.3,
        "saturated_fat": 0.1,
        "fiber": 2.6,
        "sugar": 12.2,
        "sodium": 1.0,
        "potassium": 358.0,
        "calcium": 5.0,
        "iron": 0.3,
        "glycemic_index": 51,
        "nutri_score": "A",
        "density": 0.70,
        "typical_serving_g": 80,
        "food_group": "fruits",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_potassium"]
    },
    "chia_seeds": {
        "name": "Raw Black Chia Seeds",
        "category": "Superfood / Seeds",
        "calories": 486.0,
        "protein": 16.5,
        "carbs": 42.1,
        "fat": 30.7,
        "saturated_fat": 3.3,
        "fiber": 34.4,
        "sugar": 0.0,
        "sodium": 16.0,
        "potassium": 407.0,
        "calcium": 631.0,
        "iron": 7.7,
        "glycemic_index": 1,
        "nutri_score": "A",
        "density": 0.65,
        "typical_serving_g": 15,
        "food_group": "fats",
        "tags": ["vegetarian", "vegan", "gluten_free", "omega_3", "high_fiber", "high_calcium"]
    },
    "peanut_butter": {
        "name": "Natural 100% Peanut Butter",
        "category": "Nut Butters / Fats",
        "calories": 588.0,
        "protein": 25.1,
        "carbs": 20.0,
        "fat": 50.4,
        "saturated_fat": 10.3,
        "fiber": 6.0,
        "sugar": 9.2,
        "sodium": 17.0,
        "potassium": 649.0,
        "calcium": 43.0,
        "iron": 1.9,
        "glycemic_index": 14,
        "nutri_score": "B",
        "density": 1.10,
        "typical_serving_g": 25,
        "food_group": "fats",
        "tags": ["vegetarian", "vegan", "high_protein", "monounsaturated_fat"]
    },
    "almonds_sliced": {
        "name": "Raw Sliced Almonds",
        "category": "Nuts / Fats",
        "calories": 579.0,
        "protein": 21.2,
        "carbs": 21.6,
        "fat": 49.9,
        "saturated_fat": 3.8,
        "fiber": 12.5,
        "sugar": 4.4,
        "sodium": 1.0,
        "potassium": 733.0,
        "calcium": 269.0,
        "iron": 3.7,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 0.60,
        "typical_serving_g": 20,
        "food_group": "fats",
        "tags": ["vegetarian", "vegan", "gluten_free", "high_fiber", "high_protein"]
    },
    "greek_yogurt": {
        "name": "Plain Non-Fat Greek Yogurt",
        "category": "Dairy / Protein",
        "calories": 59.0,
        "protein": 10.0,
        "carbs": 3.6,
        "fat": 0.4,
        "saturated_fat": 0.1,
        "fiber": 0.0,
        "sugar": 3.2,
        "sodium": 36.0,
        "potassium": 141.0,
        "calcium": 110.0,
        "iron": 0.1,
        "glycemic_index": 12,
        "nutri_score": "A",
        "density": 1.06,
        "typical_serving_g": 170,
        "food_group": "dairy",
        "tags": ["vegetarian", "high_protein", "low_fat", "probiotic"]
    },
    "whey_protein_shake": {
        "name": "Whey Protein Isolate Shake (Water)",
        "category": "Supplements",
        "calories": 120.0,
        "protein": 26.0,
        "carbs": 2.0,
        "fat": 0.5,
        "saturated_fat": 0.2,
        "fiber": 0.5,
        "sugar": 0.5,
        "sodium": 140.0,
        "potassium": 160.0,
        "calcium": 130.0,
        "iron": 0.4,
        "glycemic_index": 15,
        "nutri_score": "A",
        "density": 1.00,
        "typical_serving_g": 300,
        "food_group": "protein",
        "tags": ["vegetarian", "high_protein", "low_carb", "zero_fat"]
    }
}


def find_food_in_db(query: str) -> Optional[Dict[str, Any]]:
    """
    Look up a food item in the database using exact key, normalized slug, or fuzzy string match.
    """
    clean_query = query.lower().strip().replace("-", "_").replace(" ", "_")
    
    if clean_query in FOOD_DATABASE:
        item = FOOD_DATABASE[clean_query].copy()
        item["id"] = clean_query
        return item
    
    for key, data in FOOD_DATABASE.items():
        if key in clean_query or clean_query in key:
            item = data.copy()
            item["id"] = key
            return item
        if data["name"].lower() in query.lower() or query.lower() in data["name"].lower():
            item = data.copy()
            item["id"] = key
            return item

    keywords = re.findall(r"\w+", clean_query)
    for kw in keywords:
        if len(kw) < 3:
            continue
        for key, data in FOOD_DATABASE.items():
            if kw in key or kw in data["name"].lower():
                item = data.copy()
                item["id"] = key
                return item

    # Generic fallback
    return {
        "id": "generic_food",
        "name": query.title(),
        "category": "Prepared Food",
        "calories": 145.0,
        "protein": 6.5,
        "carbs": 18.0,
        "fat": 5.0,
        "saturated_fat": 1.2,
        "fiber": 2.0,
        "sugar": 2.0,
        "sodium": 220.0,
        "potassium": 180.0,
        "calcium": 40.0,
        "iron": 1.0,
        "glycemic_index": 45,
        "nutri_score": "B",
        "density": 0.95,
        "typical_serving_g": 120,
        "food_group": "composite",
        "tags": ["balanced"]
    }


def calculate_nutrients_for_portion(food_id_or_name: str, grams: float) -> Dict[str, Any]:
    """
    Calculate absolute macros and micros for a specified portion in grams.
    """
    food = find_food_in_db(food_id_or_name)
    factor = max(grams, 0.0) / 100.0

    return {
        "id": food["id"],
        "name": food["name"],
        "category": food["category"],
        "grams": round(grams, 1),
        "calories": round(food["calories"] * factor, 1),
        "protein": round(food["protein"] * factor, 1),
        "carbs": round(food["carbs"] * factor, 1),
        "fat": round(food["fat"] * factor, 1),
        "saturated_fat": round(food["saturated_fat"] * factor, 1),
        "fiber": round(food["fiber"] * factor, 1),
        "sugar": round(food["sugar"] * factor, 1),
        "sodium": round(food["sodium"] * factor, 1),
        "potassium": round(food["potassium"] * factor, 1),
        "calcium": round(food["calcium"] * factor, 1),
        "iron": round(food["iron"] * factor, 1),
        "glycemic_index": food["glycemic_index"],
        "nutri_score": food["nutri_score"],
        "food_group": food["food_group"],
        "tags": food["tags"]
    }
